# Generated by Django 2.2.1 on 2019-06-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20190613_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_limit',
            field=models.IntegerField(default=1000, max_length=30, verbose_name='User Limit'),
        ),
    ]
