# Generated by Django 2.2.1 on 2019-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20190613_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='voice_out',
            field=models.CharField(blank=True, max_length=150, verbose_name='Voice Output'),
        ),
    ]
