# Generated by Django 2.2.1 on 2019-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20190613_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coupon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_cached',
            field=models.BooleanField(default=True, verbose_name='Cached'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_limit',
            field=models.IntegerField(default=1000, verbose_name='User Limit'),
        ),
    ]
