# Generated by Django 2.2.3 on 2019-07-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_project_project_hash_enc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_hash_enc',
        ),
    ]
