# Generated by Django 2.2.3 on 2019-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_remove_project_project_hash_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_hash_enc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Project Hash Encoded'),
        ),
    ]
